# Generated by Django 3.2.5 on 2021-08-22 19:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='home', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, srid=4326)),
                ('address_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
