# Generated by Django 3.2.5 on 2021-08-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
