# Generated by Django 3.2.5 on 2021-08-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20210808_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchitem',
            name='price',
        ),
    ]
