# Generated by Django 3.2.5 on 2021-08-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_is_available_product_isavailable'),
        ('branches', '0004_remove_branchitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchitem_item', to='products.product'),
        ),
    ]
