# Generated by Django 3.2.5 on 2021-08-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_price'),
        ('orders', '0003_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='products.item', unique=True),
        ),
    ]
