# Generated by Django 3.2.5 on 2021-08-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_options'),
        ('orders', '0009_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item'),
        ),
    ]
